export const HEADER = {
  MAIN_LAYOUT_HEADER_HEIGHT_DESKTOP: 80,
  MAIN_LAYOUT_HEADER_HEIGHT_MOBILE: 70,
  PAGES_LAYOUT_HEADER_HEIGHT_DESKTOP: 80,
  PAGES_LAYOUT_HEADER_HEIGHT_MOBILE: 49,
};

export const NAVBAR = {
  MAIN_LAYOUT_NAVBAR_WIDTH_DESKTOP: 320,
  MAIN_LAYOUT_NAVBAR_WIDTH_DESKTOP_COLLAPSED: 90,
  MAIN_LAYOUT_NAVBAR_WIDTH_DESKTOP_ICON: 24,
};
